### PR TITLE
Fix bug in cart functionality and responsiveness issue

### LINKED ISSUE #24: Bug in cart functionality and responsiveness issue
## Bugs
- After reaching the max quantity, the `remove from cart` functionality is not working
- The footer is not sticking to the bottom in all screens
- There is no `not-found` or `coming soon` page, need to add them

### PR DESCRIPTION
**Pull request by kjais1720**
PR for Issue #24 ( closes #24 )
## Overview
- Fixed the bug in cart functionality 
- Fixed the footer position

### CODE REVIEW

**Review by rdshinde — APPROVED** [review]
All looks fine. Good to merge

File: src/contexts/cart&wishlist/reducer.js [hunk 1]
```diff
@@ -13,36 +12,46 @@ export const cartWishlistReducer = (state, { type, payload }) => {
...
     case "addItemToCart":
       return {
         ...state,
         apiUrl: `/api/user/cart`,
         apiMethod: "post",
         postData: { product: { ...payload, qty: 1 } },
-        toastMessage:`${payload.name} added to cart`,
-        toastType:"success"
+        toastMessage: `${payload.name} added to cart`,
+        toastType: "success",
```
Comment (ttahm3d) [inline src/contexts/cart&wishlist/reducer.js:24]: Not sure if it is good way to keep toast messages inside reducers.

**Review by srejitk — APPROVED** [review]
Looks good. No changes suggested.

**Review by ttahm3d — APPROVED** [review]
Looks good. No changes required.

File: src/contexts/cart&wishlist/reducer.js (hunk 1 above)
Comment (kjais1720) [reply src/contexts/cart&wishlist/reducer.js:24]: I just did that to avoid creating another reducer for toast messages and since the toasts would be fired only after one of cases in the reduces satisfies, so put the toast states in it
